#!/usr/bin/env bash

function mkdir_if_not_exist() {
	if [ ! -d "$1" ]; then
		echo "Creating $1"
		mkdir -p "$1"
	fi
}

mkdir_if_not_exist ~/.config/nvim
mkdir_if_not_exist ~/.config/fish
mkdir_if_not_exist ~/.config/omf
mkdir_if_not_exist ~/.terminfo

# Create nvim config directory if it doesn't exist

for d in $(ls -d */ | cut -f1 -d '/'); do
	echo "Linking $d..."
	(stow $d)
done

if [ -f /usr/bin/zsh ]; then
	# Install zplug if it doesn't exist yet
	if [ ! -d ~/.zplug ]; then
		echo "Installing zplug"
		curl -sL --proto-redir -all,https https://raw.githubusercontent.com/zplug/installer/master/installer.zsh | zsh
	fi
fi

# Install vim plugins & requirements
if [ ! "$(pip list --user | grep 'pynvim' | wc -l)" -ge 1 ]; then
	pip install --user pynvim
fi

# Install plug package manager if it doesn't exist
if [ ! -d ~/.config/nvim/plugged ]; then
	curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
		https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi
# Install nvim pluugins
nvim +PlugInstall +qall

if [ -f /usr/bin/fish ]; then
	./install.fish
fi
